# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Fidelity checks for the MicroDuck USD against the MJCF it was converted from.

``microduck_walk.usd`` is generated by ``scripts/tools/convert_microduck.py`` from ``robot_walk.xml``
of `pollen-robotics/microduck_rl <https://github.com/pollen-robotics/microduck_rl>`_; see
``ATTRIBUTION.md`` next to the asset. These tests compile the MJCF with MuJoCo, load the USD on the
Newton backend, and compare the articulation properties the locomotion task depends on, so a
re-conversion that silently drops joints, limits, mass or joint dynamics is caught here.

Every expected value is measured from the MJCF at test time; nothing is transcribed by hand.

Neither input is in the repository: USD files are excluded by ``.gitignore``, and the MJCF lives in
a pinned upstream checkout that is not vendored here. The tests therefore skip unless both are
present locally. Point ``MICRODUCK_MJCF_PATH`` at ``robot_walk.xml`` to use a checkout kept
elsewhere.
"""

import os

import numpy as np
import pytest

mujoco = pytest.importorskip("mujoco")

from isaaclab_newton.physics import NewtonCfg  # noqa: E402

from pxr import Usd, UsdGeom, UsdPhysics  # noqa: E402

import isaaclab.sim as sim_utils  # noqa: E402
from isaaclab.assets import Articulation, ArticulationCfg  # noqa: E402
from isaaclab.sim import SimulationCfg, SimulationContext  # noqa: E402

from isaaclab_assets import ISAACLAB_ASSETS_DATA_DIR  # noqa: E402

pytestmark = [pytest.mark.integration, pytest.mark.kitless]

MICRODUCK_USD_PATH = os.path.join(
    ISAACLAB_ASSETS_DATA_DIR, "Robots", "PollenRobotics", "MicroDuck", "microduck_walk.usd"
)
"""Converted asset under test."""

MICRODUCK_MJCF_PATH = os.environ.get(
    "MICRODUCK_MJCF_PATH",
    os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))),
        "artifacts/microduck/upstream/microduck_rl/src/mjlab_microduck/robot/microduck/robot_walk.xml",
    ),
)
"""Source MJCF the asset was converted from."""


@pytest.fixture(scope="module")
def mj_model():
    """The source MJCF, compiled by MuJoCo, used as the fidelity reference."""
    if not os.path.isfile(MICRODUCK_MJCF_PATH):
        pytest.skip(f"MicroDuck MJCF checkout not available: {MICRODUCK_MJCF_PATH}")
    return mujoco.MjModel.from_xml_path(MICRODUCK_MJCF_PATH)


@pytest.fixture(scope="module")
def mj_joints(mj_model):
    """Per hinge joint name: its position limits [rad] and the dynamics MuJoCo resolved for it.

    MuJoCo applies the ``chosen_actuator`` default class while compiling, so reading the compiled
    model rather than the XML text also covers the values the joints inherit.
    """
    joints = {}
    for index in range(mj_model.njnt):
        if mj_model.jnt_type[index] != mujoco.mjtJoint.mjJNT_HINGE:
            continue
        name = mujoco.mj_id2name(mj_model, mujoco.mjtObj.mjOBJ_JOINT, index)
        dof = mj_model.jnt_dofadr[index]
        joints[name] = {
            "lower": float(mj_model.jnt_range[index, 0]),
            "upper": float(mj_model.jnt_range[index, 1]),
            "armature": float(mj_model.dof_armature[dof]),
            "damping": float(mj_model.dof_damping[dof]),
            "frictionloss": float(mj_model.dof_frictionloss[dof]),
        }
    return joints


@pytest.fixture(scope="module")
def mj_actuators(mj_model):
    """Per actuated joint name: the position actuator's gains and force range from the MJCF."""
    actuators = {}
    for index in range(mj_model.nu):
        joint_id = mj_model.actuator_trnid[index, 0]
        name = mujoco.mj_id2name(mj_model, mujoco.mjtObj.mjOBJ_JOINT, joint_id)
        # MuJoCo's "position" actuator encodes gainprm=[kp, 0, ...], biasprm=[0, -kp, -kv, ...].
        actuators[name] = {
            "stiffness": float(mj_model.actuator_gainprm[index, 0]),
            "damping": float(-mj_model.actuator_biasprm[index, 2]),
            "effort_limit": float(mj_model.actuator_forcerange[index, 1]),
        }
    return actuators


@pytest.fixture(scope="module")
def usd_articulation():
    """The converted USD, loaded as a Newton articulation, plus the stage it was spawned on.

    The articulation is configured without actuators so the assertions see what the USD authored
    rather than what an :class:`~isaaclab.actuators.ActuatorBaseCfg` would write over it.
    """
    if not os.path.isfile(MICRODUCK_USD_PATH):
        pytest.skip(
            f"MicroDuck USD asset is missing: {MICRODUCK_USD_PATH}. Generate it with"
            " 'uv run --extra importers python scripts/tools/convert_microduck.py <robot_walk.xml>'."
        )

    sim_utils.create_new_stage()
    sim = SimulationContext(SimulationCfg(dt=0.005, device="cuda:0", physics=NewtonCfg()))
    robot = Articulation(
        ArticulationCfg(prim_path="/World/Robot", spawn=sim_utils.UsdFileCfg(usd_path=MICRODUCK_USD_PATH), actuators={})
    )
    sim.reset()

    yield robot, sim.stage

    sim.stop()
    sim.clear_instance()


def test_actuated_joint_names_match_mjcf(usd_articulation, mj_joints):
    """Every MJCF hinge joint survives the conversion, with no extras."""
    robot, _ = usd_articulation
    assert set(robot.joint_names) == set(mj_joints)


def test_joint_position_limits_match_mjcf(usd_articulation, mj_joints):
    """Each joint keeps both of its MJCF limits, which are asymmetric for the head joints."""
    robot, _ = usd_articulation
    limits = robot.data.joint_pos_limits.torch[0].cpu().numpy()
    for index, name in enumerate(robot.joint_names):
        assert limits[index, 0] == pytest.approx(mj_joints[name]["lower"], abs=1e-5)
        assert limits[index, 1] == pytest.approx(mj_joints[name]["upper"], abs=1e-5)


def test_joint_armature_matches_mjcf(usd_articulation, mj_joints):
    """Armature survives conversion, so the task inherits the MJCF rotor inertia."""
    robot, _ = usd_articulation
    armature = robot.data.joint_armature.torch[0].cpu().numpy()
    for index, name in enumerate(robot.joint_names):
        assert armature[index] == pytest.approx(mj_joints[name]["armature"], rel=1e-5)


def test_joint_effort_limits_match_mjcf(usd_articulation, mj_actuators):
    """The actuator force range survives conversion as the joint effort limit."""
    robot, _ = usd_articulation
    effort_limits = robot.data.joint_effort_limits.torch[0].cpu().numpy()
    for index, name in enumerate(robot.joint_names):
        assert effort_limits[index] == pytest.approx(mj_actuators[name]["effort_limit"], rel=1e-5)


def test_joint_dynamics_not_carried_by_the_asset(usd_articulation, mj_joints, mj_actuators):
    """Pin the joint dynamics the conversion does *not* carry, which the task config must supply.

    The MJCF importer refuses to translate the ``position`` actuator gains ("Gain and bias prm
    arrays are not in the expected format ... physics drive stiffness and damping will not be
    created") and writes joint damping and friction only as ``mjc:*`` attributes, which are not in
    the schema resolver set Isaac Lab passes to Newton's USD importer. All four therefore arrive as
    zero and are owned by the task's actuator configuration. Asserting that keeps a future importer
    that starts authoring them from silently doubling up with the actuator config.
    """
    robot, _ = usd_articulation
    stiffness = robot.data.joint_stiffness.torch[0].cpu().numpy()
    damping = robot.data.joint_damping.torch[0].cpu().numpy()
    friction = robot.data.joint_friction_coeff.torch[0].cpu().numpy()

    # the MJCF values that the asset does not carry, guarding against a no-op comparison
    assert all(mj_actuators[name]["stiffness"] > 0.0 for name in robot.joint_names)
    assert all(mj_joints[name]["damping"] > 0.0 for name in robot.joint_names)
    assert all(mj_joints[name]["frictionloss"] > 0.0 for name in robot.joint_names)

    assert np.all(stiffness == 0.0)
    assert np.all(damping == 0.0)
    assert np.all(friction == 0.0)


def test_total_mass_matches_mjcf(usd_articulation, mj_model):
    """The converted articulation carries the same total mass as the MJCF."""
    robot, _ = usd_articulation
    expected_mass = float(np.sum(mj_model.body_mass))
    assert float(robot.data.body_mass.torch[0].sum()) == pytest.approx(expected_mass, rel=0.01)


def test_root_body_height_matches_mjcf(usd_articulation, mj_model):
    """The root body keeps the MJCF home height, so the task can reuse the upstream spawn pose."""
    _, stage = usd_articulation
    root_prim = next(
        prim
        for prim in Usd.PrimRange(stage.GetPrimAtPath("/World/Robot"))
        if prim.HasAPI(UsdPhysics.ArticulationRootAPI)
    )
    transform = UsdGeom.Xformable(root_prim).ComputeLocalToWorldTransform(Usd.TimeCode.Default())
    assert float(transform.ExtractTranslation()[2]) == pytest.approx(float(mj_model.qpos0[2]), abs=1e-3)


def test_floating_base(usd_articulation):
    """The conversion must not weld the root to the world; the walk task needs a floating base."""
    robot, _ = usd_articulation
    assert not robot.is_fixed_base
