# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Tests for the MicroDuck conversion tooling, the USD it produces, and ``MICRODUCK_CFG``.

``microduck_walk.usd`` is generated by ``scripts/tools/convert_microduck.py`` from ``robot_walk.xml``
of `pollen-robotics/microduck_rl <https://github.com/pollen-robotics/microduck_rl>`_; see
``ATTRIBUTION.md`` next to the asset.

Three layers of tests live here:

* Converter tests, which import ``convert_microduck.py`` and exercise its pinned provenance and its
  stage repairs on a stage authored in the test. These need no asset and never skip.
* Fidelity tests, which compile the MJCF with MuJoCo, load the USD on the Newton backend, and
  compare the articulation properties the locomotion task depends on, so a re-conversion that
  silently drops joints, limits, mass, joint dynamics or contact properties is caught. Every
  expected value is measured from the MJCF at test time; nothing is transcribed by hand.
* Configuration tests, which spawn :data:`~isaaclab_assets.MICRODUCK_CFG` and check that it pins
  upstream's servo deployment and leaves the properties the conversion cannot carry to the model
  that owns them.

The fidelity tests' inputs are not in the repository: USD files are excluded by ``.gitignore``, and
the MJCF is fetched from the pinned upstream commit into a local cache. They skip unless both are
present. Generate them with ``uv run --extra importers python scripts/tools/convert_microduck.py``,
or point ``MICRODUCK_MJCF_PATH`` at a ``robot_walk.xml`` kept elsewhere.
"""

import copy
import importlib.util
import os

import numpy as np
import pytest
from isaaclab_newton.physics import NewtonCfg

from pxr import Gf, Sdf, Usd, UsdGeom, UsdPhysics, UsdShade

import isaaclab.sim as sim_utils
from isaaclab.assets import Articulation, ArticulationCfg
from isaaclab.sim import SimulationCfg, SimulationContext

from isaaclab_assets import MICRODUCK_CFG
from isaaclab_assets.robots.microduck import MICRODUCK_REGENERATE_COMMAND, MICRODUCK_USD_PATH

pytestmark = [pytest.mark.integration, pytest.mark.kitless]

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

CONVERTER_SCRIPT_PATH = os.path.join(_REPO_ROOT, "scripts", "tools", "convert_microduck.py")
"""Conversion script under test."""

MICRODUCK_MJCF_PATH = os.environ.get("MICRODUCK_MJCF_PATH", "")
"""Override for the source MJCF. Empty means the converter's pinned upstream cache is used."""

NUM_ACTUATED_JOINTS = 14
"""Joint count ``robot_walk.xml`` is known to have, guarding against a partial import that still
matches the MJCF because both sides were read from the same truncated model."""

HOME_POSE = {
    "left_hip_yaw": 0.0,
    "right_hip_yaw": 0.0,
    "left_hip_roll": -0.0873,
    "right_hip_roll": 0.0873,
    "left_hip_pitch": -0.4579,
    "right_hip_pitch": 0.4579,
    "left_knee": -0.0049,
    "right_knee": 0.0049,
    "left_ankle": 0.4530,
    "right_ankle": -0.4530,
    "neck_pitch": 0.3491,
    "head_pitch": 0.3491,
    "head_yaw": 0.0,
    "head_roll": 0.0,
}
"""Upstream ``HOME_FRAME`` (STAND2), transcribed per joint name from ``microduck_constants.py``.

The configuration expresses it with regular expressions, so spelling it out one joint at a time is
what makes the check meaningful: a pattern that matches nothing leaves the joint at zero.
"""

UPSTREAM_RESET_HEIGHT_RANGE = (0.12, 0.13)
"""Base height [m] upstream's ``reset_base`` event samples, from ``microduck_rl``."""


@pytest.fixture(scope="module")
def converter():
    """The conversion script, imported as a module.

    It is a standalone script rather than an installed package, so it is loaded from its path. The
    script keeps argument parsing inside ``main`` precisely so that importing it is side-effect free.
    """
    spec = importlib.util.spec_from_file_location("convert_microduck", CONVERTER_SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def mjcf_path(converter):
    """Path to the source MJCF, from the override or the converter's pinned upstream cache."""
    if MICRODUCK_MJCF_PATH:
        return MICRODUCK_MJCF_PATH
    try:
        return converter.resolve_source_mjcf()
    except Exception as exc:  # noqa: BLE001 - any fetch failure is a skip, not a test failure
        pytest.skip(f"MicroDuck MJCF is not available and could not be fetched: {exc}")


@pytest.fixture(scope="module")
def mj_model(mjcf_path):
    """The source MJCF, compiled by MuJoCo, used as the fidelity reference."""
    mujoco = pytest.importorskip("mujoco")
    if not os.path.isfile(mjcf_path):
        pytest.skip(f"MicroDuck MJCF checkout not available: {mjcf_path}")
    return mujoco.MjModel.from_xml_path(mjcf_path)


@pytest.fixture(scope="module")
def mj_joints(mj_model):
    """Per hinge joint name: its position limits [rad] and the dynamics MuJoCo resolved for it.

    MuJoCo applies the ``chosen_actuator`` default class while compiling, so reading the compiled
    model rather than the XML text also covers the values the joints inherit.
    """
    import mujoco

    joints = {}
    for index in range(mj_model.njnt):
        if mj_model.jnt_type[index] != mujoco.mjtJoint.mjJNT_HINGE:
            continue
        name = mujoco.mj_id2name(mj_model, mujoco.mjtObj.mjOBJ_JOINT, index)
        dof = mj_model.jnt_dofadr[index]
        joints[name] = {
            "lower": float(mj_model.jnt_range[index, 0]),
            "upper": float(mj_model.jnt_range[index, 1]),
            "armature": float(mj_model.dof_armature[dof]),
            "damping": float(mj_model.dof_damping[dof]),
            "frictionloss": float(mj_model.dof_frictionloss[dof]),
        }
    return joints


@pytest.fixture(scope="module")
def mj_actuators(mj_model):
    """Per actuated joint name: the position actuator's gains and force range from the MJCF."""
    import mujoco

    actuators = {}
    for index in range(mj_model.nu):
        joint_id = mj_model.actuator_trnid[index, 0]
        name = mujoco.mj_id2name(mj_model, mujoco.mjtObj.mjOBJ_JOINT, joint_id)
        # MuJoCo's "position" actuator encodes gainprm=[kp, 0, ...], biasprm=[0, -kp, -kv, ...].
        actuators[name] = {
            "stiffness": float(mj_model.actuator_gainprm[index, 0]),
            "damping": float(-mj_model.actuator_biasprm[index, 2]),
            "effort_limit": float(mj_model.actuator_forcerange[index, 1]),
        }
    return actuators


@pytest.fixture(scope="module")
def mj_world_colliders(mj_model):
    """The MJCF geoms that can touch the ground, and the friction MuJoCo resolved for them.

    A ground plane carries the default ``contype``/``conaffinity`` of 1, so a geom reaches world
    contact only when both of its masks share that bit. The ``self_collision_only`` geoms use 2 and
    are excluded, which is exactly the distinction the conversion has to reproduce.
    """
    import mujoco

    colliders = {}
    for index in range(mj_model.ngeom):
        if not (mj_model.geom_contype[index] & 1 and mj_model.geom_conaffinity[index] & 1):
            continue
        name = mujoco.mj_id2name(mj_model, mujoco.mjtObj.mjOBJ_GEOM, index)
        sliding, torsional, rolling = (float(value) for value in mj_model.geom_friction[index])
        colliders[name] = {"sliding": sliding, "torsional": torsional, "rolling": rolling}
    return colliders


@pytest.fixture(scope="module")
def newton_articulations():
    """The converted USD spawned twice on one Newton stage: bare, and through ``MICRODUCK_CFG``.

    The bare articulation carries no actuators, so the fidelity assertions see what the USD authored
    rather than what an :class:`~isaaclab.actuators.ActuatorBaseCfg` would write over it. The
    configured one is what a task instantiates. Both share one simulation because
    :class:`~isaaclab.sim.SimulationContext` is a singleton; the configured robot is offset in x so
    the two do not overlap.

    The bare articulation has no initial state, and the conversion clears the root transform, so it
    spawns with its feet below the origin. That is harmless here: none of these tests steps the
    simulation, and the stage carries no ground plane.
    """
    if not os.path.isfile(MICRODUCK_USD_PATH):
        pytest.skip(
            f"MicroDuck USD asset is missing: {MICRODUCK_USD_PATH}. Generate it with"
            " 'uv run --extra importers python scripts/tools/convert_microduck.py <robot_walk.xml>'."
        )

    sim_utils.create_new_stage()
    sim = SimulationContext(SimulationCfg(dt=0.005, device="cuda:0", physics=NewtonCfg()))
    bare = Articulation(
        ArticulationCfg(prim_path="/World/Robot", spawn=sim_utils.UsdFileCfg(usd_path=MICRODUCK_USD_PATH), actuators={})
    )
    configured_cfg = copy.deepcopy(MICRODUCK_CFG)
    configured_cfg.prim_path = "/World/MicroDuck"
    configured_cfg.init_state.pos = (1.0, 0.0, MICRODUCK_CFG.init_state.pos[2])
    configured = Articulation(configured_cfg)
    sim.reset()

    yield bare, configured, sim.stage

    sim.stop()
    sim.clear_instance()


@pytest.fixture(scope="module")
def usd_articulation(newton_articulations):
    """The articulation loaded straight from the USD, plus the stage it was spawned on."""
    bare, _, stage = newton_articulations
    return bare, stage


@pytest.fixture(scope="module")
def microduck_articulation(newton_articulations):
    """The articulation loaded through :data:`~isaaclab_assets.MICRODUCK_CFG`."""
    return newton_articulations[1]


def test_converter_pins_its_upstream_source(converter):
    """The conversion is reproducible: the MJCF comes from one fixed upstream commit.

    ``robot_walk.xml`` is regenerated from CAD upstream, so tracking a branch would silently change
    the asset. The provenance recorded in ``ATTRIBUTION.md`` is only true if this stays pinned.
    """
    assert converter.MICRODUCK_REPO_URL == "https://github.com/pollen-robotics/microduck_rl.git"
    assert converter.MICRODUCK_REV == "d424a0c899f6b33cbd3daeb279913134349c0b63"
    assert len(converter.MICRODUCK_REV) == 40, "a short SHA is ambiguous, pin the full one"
    assert converter.MICRODUCK_MJCF_REPO_PATH.endswith("/robot_walk.xml")


def test_converter_writes_where_the_asset_is_loaded_from(converter):
    """The script's default output is the path the asset config and these tests read."""
    assert os.path.normpath(converter.MICRODUCK_USD_PATH) == os.path.normpath(MICRODUCK_USD_PATH)


def test_resolve_source_mjcf_requests_the_pinned_revision(converter, monkeypatch):
    """The pinned commit reaches the fetch, rather than defaulting to the upstream branch."""
    import isaaclab.utils.assets as assets_utils

    calls = []
    monkeypatch.setattr(
        assets_utils, "retrieve_git_asset_path", lambda *args, **kwargs: calls.append((args, kwargs)) or "/mjcf.xml"
    )

    assert converter.resolve_source_mjcf() == "/mjcf.xml"
    (args, kwargs) = calls[0]
    assert args == (converter.MICRODUCK_REPO_URL, converter.MICRODUCK_MJCF_REPO_PATH)
    assert kwargs == {"rev": converter.MICRODUCK_REV}


def test_flatten_repairs_what_the_importer_loses(converter, tmp_path):
    """``flatten_to_single_file`` binds the foot colliders, disables the rest, and clears the root.

    The MJCF importer loses the contact properties to scene-graph instancing and bakes the MJCF home
    height into the articulation root (see the script's docstring). The contact fix has to survive
    the case that makes it hard: one prototype shared between a collider that must stay enabled and
    one that must not. All of it is reproduced here rather than read off the generated asset, so this
    runs without any converted USD present.
    """
    source_path = tmp_path / "layered.usda"
    stage = Usd.Stage.CreateNew(str(source_path))

    root = UsdGeom.Xform.Define(stage, "/Model")
    UsdPhysics.ArticulationRootAPI.Apply(root.GetPrim())
    root.AddTranslateOp().Set(Gf.Vec3d(0.0, 0.0, 0.12))
    root.AddOrientOp().Set(Gf.Quatf(1.0, Gf.Vec3f(0.0, 0.0, 0.0)))

    material = UsdShade.Material.Define(stage, "/Model/Physics/PhysicsMaterial")
    UsdPhysics.MaterialAPI.Apply(material.GetPrim())

    # ``Flatten`` emits prototypes as class prims, so the repairs must not reach into them; the
    # shared prototype below is what makes editing through an instance proxy the wrong move.
    prototype = stage.DefinePrim("/Prototypes/Sole", "Xform")
    prototype.SetSpecifier(Sdf.SpecifierClass)
    UsdPhysics.CollisionAPI.Apply(stage.DefinePrim("/Prototypes/Sole/geom", "Cube"))

    for path in ("/Model/left_foot_collision", "/Model/shell"):
        instance = stage.DefinePrim(path, "Xform")
        instance.GetReferences().AddInternalReference("/Prototypes/Sole")
        instance.SetInstanceable(True)
    stage.Save()

    dest_path = tmp_path / "out" / "flattened.usd"
    converter.flatten_to_single_file(str(source_path), str(dest_path))

    assert dest_path.is_file(), "the flattened asset is written as a single file"
    flattened = Usd.Stage.Open(str(dest_path))
    foot = flattened.GetPrimAtPath("/Model/left_foot_collision/geom")
    shell = flattened.GetPrimAtPath("/Model/shell/geom")

    assert UsdPhysics.CollisionAPI(foot).GetCollisionEnabledAttr().Get() is not False
    assert UsdPhysics.CollisionAPI(shell).GetCollisionEnabledAttr().Get() is False
    bound_material, _ = UsdShade.MaterialBindingAPI(foot).ComputeBoundMaterial("physics")
    assert bound_material.GetPrim().GetPath() == material.GetPrim().GetPath()

    flattened_root = UsdGeom.Xformable(flattened.GetPrimAtPath("/Model"))
    assert flattened_root.ComputeLocalToWorldTransform(Usd.TimeCode.Default()) == Gf.Matrix4d(1.0)
    assert not [name for name in flattened.GetPrimAtPath("/Model").GetPropertyNames() if name.startswith("xformOp:")]


def test_actuated_joint_names_match_mjcf(usd_articulation, mj_joints):
    """Every MJCF hinge joint survives the conversion, with no extras."""
    robot, _ = usd_articulation
    assert len(mj_joints) == NUM_ACTUATED_JOINTS
    assert set(robot.joint_names) == set(mj_joints)


def test_joint_position_limits_match_mjcf(usd_articulation, mj_joints):
    """Each joint keeps both of its MJCF limits, which are asymmetric for the head joints."""
    robot, _ = usd_articulation
    limits = robot.data.joint_pos_limits.torch[0].cpu().numpy()
    for index, name in enumerate(robot.joint_names):
        assert limits[index, 0] == pytest.approx(mj_joints[name]["lower"], abs=1e-5)
        assert limits[index, 1] == pytest.approx(mj_joints[name]["upper"], abs=1e-5)


def test_joint_armature_matches_mjcf(usd_articulation, mj_joints):
    """Armature survives conversion, so the task inherits the MJCF rotor inertia."""
    robot, _ = usd_articulation
    armature = robot.data.joint_armature.torch[0].cpu().numpy()
    for index, name in enumerate(robot.joint_names):
        assert armature[index] == pytest.approx(mj_joints[name]["armature"], rel=1e-5)


def test_joint_effort_limits_match_mjcf(usd_articulation, mj_actuators):
    """The actuator force range survives conversion as the joint effort limit."""
    robot, _ = usd_articulation
    effort_limits = robot.data.joint_effort_limits.torch[0].cpu().numpy()
    for index, name in enumerate(robot.joint_names):
        assert effort_limits[index] == pytest.approx(mj_actuators[name]["effort_limit"], rel=1e-5)


def test_joint_dynamics_not_carried_by_the_asset(usd_articulation, mj_joints, mj_actuators):
    """Pin the joint dynamics the conversion does *not* carry, which the task config must supply.

    The MJCF importer refuses to translate the ``position`` actuator gains ("Gain and bias prm
    arrays are not in the expected format ... physics drive stiffness and damping will not be
    created") and writes joint damping and friction only as ``mjc:*`` attributes, which are not in
    the schema resolver set Isaac Lab passes to Newton's USD importer. All four therefore arrive as
    zero and are owned by the servo model instead. Asserting that keeps a future importer that
    starts authoring them from silently doubling up with the actuator.
    """
    robot, _ = usd_articulation
    stiffness = robot.data.joint_stiffness.torch[0].cpu().numpy()
    damping = robot.data.joint_damping.torch[0].cpu().numpy()
    friction = robot.data.joint_friction_coeff.torch[0].cpu().numpy()

    # the MJCF values that the asset does not carry, guarding against a no-op comparison
    assert all(mj_actuators[name]["stiffness"] > 0.0 for name in robot.joint_names)
    assert all(mj_joints[name]["damping"] > 0.0 for name in robot.joint_names)
    assert all(mj_joints[name]["frictionloss"] > 0.0 for name in robot.joint_names)

    assert np.all(stiffness == 0.0)
    assert np.all(damping == 0.0)
    assert np.all(friction == 0.0)


def test_total_mass_matches_mjcf(usd_articulation, mj_model):
    """The converted articulation carries the same total mass as the MJCF."""
    robot, _ = usd_articulation
    expected_mass = float(np.sum(mj_model.body_mass))
    assert float(robot.data.body_mass.torch[0].sum()) == pytest.approx(expected_mass, rel=0.01)


def test_root_transform_lets_the_configuration_set_the_spawn_height(usd_articulation, mj_model):
    """The MJCF home height is owned by the configuration, not baked into the root transform.

    The importer writes the MJCF's ``qpos0`` into the articulation root's own transform. Spawning
    applies a configuration's initial position to the prim the asset is referenced under, so a baked
    transform composes with it and doubles the spawn height. The conversion clears it; the height
    moves to :data:`~isaaclab_assets.MICRODUCK_CFG`, which must still cover the MJCF's.
    """
    _, stage = usd_articulation
    root_prim = next(
        prim
        for prim in Usd.PrimRange(stage.GetPrimAtPath("/World/Robot"))
        if prim.HasAPI(UsdPhysics.ArticulationRootAPI)
    )
    transform = UsdGeom.Xformable(root_prim).ComputeLocalToWorldTransform(Usd.TimeCode.Default())
    assert transform == Gf.Matrix4d(1.0), "the articulation root must spawn at its parent's origin"

    low, high = UPSTREAM_RESET_HEIGHT_RANGE
    assert low <= float(mj_model.qpos0[2]) <= high
    assert MICRODUCK_CFG.init_state.pos[2] == pytest.approx((low + high) / 2.0)


def test_floating_base(usd_articulation):
    """The conversion must not weld the root to the world; the walk task needs a floating base."""
    robot, _ = usd_articulation
    assert not robot.is_fixed_base


def _enabled_colliders(stage) -> list[Usd.Prim]:
    """Return the spawned prims that can take part in world contact."""
    return [
        prim
        for prim in Usd.PrimRange(stage.GetPrimAtPath("/World/Robot"), Usd.TraverseInstanceProxies())
        if prim.HasAPI(UsdPhysics.CollisionAPI)
        and UsdPhysics.CollisionAPI(prim).GetCollisionEnabledAttr().Get() is not False
    ]


def test_world_colliders_match_mjcf(usd_articulation, mj_world_colliders):
    """Only the geoms the MJCF lets touch the ground are enabled colliders.

    The importer authors no collision groups or filtered pairs, so without the conversion's repair
    the ``self_collision_only`` shells would drag along the terrain.
    """
    _, stage = usd_articulation
    colliders = _enabled_colliders(stage)

    assert len(mj_world_colliders) == 2, "the MJCF's world-contact set is the two foot soles"
    assert len(colliders) == len(mj_world_colliders)
    # the MJCF geoms are named '<side>_foot_collision'; the USD keeps that name on the parent Xform
    assert {prim.GetParent().GetName() for prim in colliders} == set(mj_world_colliders)


def test_foot_friction_matches_mjcf(usd_articulation, mj_world_colliders):
    """Each foot collider resolves to a physics material carrying the MJCF friction."""
    _, stage = usd_articulation

    for prim in _enabled_colliders(stage):
        expected = mj_world_colliders[prim.GetParent().GetName()]
        material, _ = UsdShade.MaterialBindingAPI(prim).ComputeBoundMaterial("physics")
        assert material, f"no physics material bound to {prim.GetPath()}"

        material_api = UsdPhysics.MaterialAPI(material.GetPrim())
        # MuJoCo has one sliding coefficient where UsdPhysics has a static and a dynamic one
        assert material_api.GetStaticFrictionAttr().Get() == pytest.approx(expected["sliding"], rel=1e-5)
        assert material_api.GetDynamicFrictionAttr().Get() == pytest.approx(expected["sliding"], rel=1e-5)
        torsional = material.GetPrim().GetAttribute("newton:torsionalFriction").Get()
        rolling = material.GetPrim().GetAttribute("newton:rollingFriction").Get()
        assert torsional == pytest.approx(expected["torsional"], rel=1e-5)
        assert rolling == pytest.approx(expected["rolling"], rel=1e-5)


def test_microduck_cfg_actuates_every_joint(microduck_articulation):
    """The servo group's expression reaches all 14 joints and no joint is left undriven."""
    robot = microduck_articulation
    assert set(robot.actuators) == {"servos"}

    servos = robot.actuators["servos"]
    assert len(servos.joint_names) == NUM_ACTUATED_JOINTS
    assert set(servos.joint_names) == set(robot.joint_names)


def test_microduck_cfg_default_joint_pos_is_the_home_pose(microduck_articulation):
    """Every joint resets to its upstream ``HOME_FRAME`` value."""
    robot = microduck_articulation
    default_joint_pos = robot.data.default_joint_pos.torch[0].cpu().numpy()
    assert len(HOME_POSE) == NUM_ACTUATED_JOINTS

    for index, name in enumerate(robot.joint_names):
        assert default_joint_pos[index] == pytest.approx(HOME_POSE[name], abs=1e-6), name


def test_microduck_cfg_restores_the_joint_dynamics_the_asset_drops(microduck_articulation, mj_joints):
    """The passive dynamics lost in conversion come back through the actuator configuration.

    ``test_joint_dynamics_not_carried_by_the_asset`` pins that the USD arrives with zero joint
    damping and friction. The configuration owns them instead, as viscous friction (MuJoCo's
    ``dof_damping``) and dry friction (``frictionloss``) rather than as PD gains, which the BAM
    model would never read. On the Isaac Lab-executed path they are the only joint-level
    dissipation the solver has, and it diverges without them; on the Newton-native path the
    controller republishes its own budget over them every physics step, so they are seeds there.

    The viscous coefficient is deliberately *not* the MJCF's ``dof_damping``: upstream's BAM binding
    overwrites that with the servo fit's ``friction_viscous`` every step, so the fit is what the
    deployed robot runs at, and the two differ by an order of magnitude. The comparison is against
    the vendored fit the actuator loaded rather than against
    :data:`~isaaclab_assets.robots.microduck.MICRODUCK_JOINT_DAMPING`, so the configured constant is
    checked against an independent source.
    """
    robot = microduck_articulation
    servos = robot.actuators["servos"]
    viscous = robot.data.joint_viscous_friction_coeff.torch[0].cpu().numpy()
    friction = robot.data.joint_friction_coeff.torch[0].cpu().numpy()
    armature = robot.data.joint_armature.torch[0].cpu().numpy()

    # the MJCF value is ten times the fit, so a revert to it cannot pass the comparison below
    assert all(mj_joints[name]["damping"] > 5.0 * servos.params.friction_viscous for name in robot.joint_names)

    for index, name in enumerate(robot.joint_names):
        # rel=1e-3 because the configured constant is the fit rounded to three significant digits
        assert viscous[index] == pytest.approx(servos.params.friction_viscous, rel=1e-3), name
        assert friction[index] == pytest.approx(mj_joints[name]["frictionloss"], rel=1e-4), name
        # armature is left to the USD, which carries the MJCF value unchanged
        assert armature[index] == pytest.approx(mj_joints[name]["armature"], rel=1e-4), name
        # ... and the BAM fit identifies that same reflected rotor inertia, which the MJCF writes
        # rounded to two significant digits
        assert servos.params.armature == pytest.approx(mj_joints[name]["armature"], rel=1e-2), name


def test_microduck_cfg_servo_model_is_upstreams_bam_deployment(microduck_articulation, mj_actuators):
    """The servo group is the BAM model at upstream's deployment settings, cross-checked on the MJCF.

    Upstream's ``_BAM_ACTUATOR_KWARGS`` (reference section 6) are pinned field by field, because a
    silent change to any of them retrains a different robot. The gains are then cross-checked
    against the MJCF: the small-signal stiffness of the firmware loop at the middle of the battery
    range, ``kp_fw * error_gain * vin * kt / R``, is an independent re-derivation of the ``kp``
    the MJCF's fallback ``position`` actuator declares. The model's own effort limit is upstream's
    electrical stall torque at the top of the battery range, which sits *above* the MJCF's
    ``forcerange`` -- so the solver clamp, which conversion carries unchanged, binds first.
    """
    robot = microduck_articulation
    servos = robot.actuators["servos"]
    cfg = servos.cfg
    params = servos.params
    solver_limit = robot.data.joint_effort_limits.torch[0].cpu().numpy()

    assert cfg.kp_fw == 200.0
    assert cfg.vin_range == (6.5, 8.2)
    assert cfg.vin_drop_gain_range == (0.0, 0.2)
    assert cfg.vin_min == 6.0
    assert cfg.friction_scale_range == (0.9, 1.1)
    assert (cfg.min_delay, cfg.max_delay) == (3, 6)
    # unused by this model, and set to anything but None they warn
    assert cfg.stiffness is None and cfg.damping is None

    nominal_vin = sum(cfg.vin_range) / 2.0
    small_signal_stiffness = cfg.kp_fw * params.error_gain * nominal_vin * params.kt / params.R
    stall_torque = max(cfg.vin_range) * params.kt / params.R
    for index, name in enumerate(robot.joint_names):
        authored = mj_actuators[name]["effort_limit"]
        assert small_signal_stiffness == pytest.approx(mj_actuators[name]["stiffness"], rel=0.01), name
        assert float(servos.actuator_effort_limit[0, index]) == pytest.approx(stall_torque, rel=1e-6), name
        assert float(servos.actuator_effort_limit[0, index]) > authored, name
        assert solver_limit[index] == pytest.approx(authored, rel=1e-5), name


def test_microduck_cfg_reports_a_missing_asset_with_the_command_that_makes_it(tmp_path):
    """A missing asset fails with the command that regenerates it, rather than a bare USD error.

    The asset is generated rather than committed, so this is the first thing a fresh checkout hits.
    The check lives on the spawner instead of at import time, which keeps the configuration
    inspectable without the asset -- the condition the fidelity fixtures skip on.
    """
    spawn = copy.deepcopy(MICRODUCK_CFG.spawn)
    spawn.usd_path = str(tmp_path / "microduck_walk.usd")

    with pytest.raises(FileNotFoundError) as excinfo:
        spawn.func("/World/Robot", spawn)

    assert MICRODUCK_REGENERATE_COMMAND in str(excinfo.value)
    assert "convert_microduck.py" in MICRODUCK_REGENERATE_COMMAND
