# Attach current receptors to a rigid object / articulation / rigid object collection

# It should be able to detect the current velocity at a point in the fluid.
# Based on the current velocity and the viscosity of the fluid, it should be able to calculate the a push force generated by the current.
# Should be able to select the bodies to apply the current to. I.e. separate the current from the hull of a ship to its sails.
# Want to support different basic shapes for the receptors. Like sphere, cylinder, box and plane.